date = input("training date: ")
table_size = input("table size: ")
training_item = input("training item: ")
total_shot = int(input("total shot: "))
made_shot = int(input("made shot: "))
mental_score = input("mental score(1-5): ")
hit_percent = made_shot / total_shot * 100
print("\n========== Today's snooker training record ==========")
print(f"training item: {training_item}")
print(f"table size: {table_size}")
print(f"training date: {date}")
print(f"total shot: {total_shot}, made shot: {made_shot}")
print(f"hit percent: {hit_percent:.1f} %")
print(f"mental score: {mental_score}")